name: 'dbt_learning'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  
models:
  dbt_learning:      # <- use your actual project name here, check the top of dbt_project.yml
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table